#!/bin/bash
# Installer for the Daly BMS monitor service
# Installs Python files, creates a config, and sets up a systemd user service.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${DALYMON_INSTALL_DIR:-$HOME/.local/lib/dalymon}"
CONFIG_DIR="$HOME/.config/dalymon"
SERVICE_FILE="$HOME/.config/systemd/user/dalymon.service"
VENV_DIR="$INSTALL_DIR/.venv"
PYTHON="python3"

# ── helpers ──────────────────────────────────────────────────────────────────

bold()  { printf '\033[1m%s\033[0m' "$*"; }
info()  { echo "  $(bold '→') $*"; }
ok()    { echo "  ✓ $*"; }
warn()  { echo "  ⚠ $*"; }
die()   { echo "ERROR: $*" >&2; exit 1; }

ask() {
    # ask <variable> <prompt> [default]
    local var="$1" prompt="$2" default="$3"
    local display_default=""
    [[ -n "$default" ]] && display_default=" [$default]"
    while true; do
        read -rp "  ${prompt}${display_default}: " value
        value="${value:-$default}"
        [[ -n "$value" ]] && break
        echo "    This field is required." >&2
    done
    printf -v "$var" '%s' "$value"
}

ask_optional() {
    # ask_optional <variable> <prompt> [default]
    local var="$1" prompt="$2" default="$3"
    local display_default=""
    [[ -n "$default" ]] && display_default=" [$default]"
    read -rp "  ${prompt}${display_default}: " value
    printf -v "$var" '%s' "${value:-$default}"
}

ask_bt_address() {
    # ask_bt_address <variable> <prompt>
    local var="$1" prompt="$2" value
    while true; do
        read -rp "  ${prompt}: " value
        if [[ "$value" =~ ^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$ ]]; then
            break
        fi
        echo "    Please enter a valid Bluetooth MAC address (e.g. AA:BB:CC:DD:EE:FF)." >&2
    done
    printf -v "$var" '%s' "$value"
}

# ── header ────────────────────────────────────────────────────────────────────

echo ""
echo "$(bold 'Daly BMS Monitor – Installer')"
echo "────────────────────────────────────────"
echo ""

# ── gather InfluxDB settings ─────────────────────────────────────────────────

echo "$(bold 'InfluxDB connection')"
ask       INFLUX_URL    "InfluxDB URL"        "http://localhost:8086"
ask       INFLUX_ORG    "InfluxDB org"        "boat_systems"
ask       INFLUX_BUCKET "InfluxDB bucket"     "power_telemetry"
ask       INFLUX_TOKEN  "InfluxDB token"

echo ""

# ── gather battery info ───────────────────────────────────────────────────────

echo "$(bold 'Battery configuration')"
echo "  (You can add more batteries by editing $CONFIG_DIR/daly.conf after install)"
echo ""
ask        BATTERY_NAME    "Battery name"     "Hausbatterie"
ask_bt_address BATTERY_ADDR "Bluetooth address (AA:BB:CC:DD:EE:FF)"

echo ""

# ── confirm ───────────────────────────────────────────────────────────────────

echo "$(bold 'Installation plan')"
echo "  Install directory : $INSTALL_DIR"
echo "  Config directory  : $CONFIG_DIR"
echo "  Systemd service   : $SERVICE_FILE"
echo "  InfluxDB URL      : $INFLUX_URL"
echo "  InfluxDB org      : $INFLUX_ORG"
echo "  InfluxDB bucket   : $INFLUX_BUCKET"
echo "  InfluxDB token    : ${INFLUX_TOKEN:0:8}…  (truncated)"
echo "  Battery           : $BATTERY_NAME  ($BATTERY_ADDR)"
echo ""
read -rp "  Continue? [Y/n] " yn
case "${yn:-Y}" in
    [Yy]*) ;;
    *) echo "Aborted."; exit 0 ;;
esac
echo ""

# ── install Python files ──────────────────────────────────────────────────────

info "Creating install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

PYTHON_FILES=(
    dalymon.py
    health_assessment.py
    import_jsonl_to_influx.py
    report.py
    scan.py
    reset_influx_password.py
)

for f in "${PYTHON_FILES[@]}"; do
    if [[ -f "$SCRIPT_DIR/$f" ]]; then
        install -m 644 "$SCRIPT_DIR/$f" "$INSTALL_DIR/"
        ok "Installed $f"
    else
        warn "Source file not found, skipping: $f"
    fi
done

# ── set up Python virtual environment ─────────────────────────────────────────

if [[ ! -d "$VENV_DIR" ]]; then
    info "Creating Python virtual environment in $VENV_DIR"
    "$PYTHON" -m venv "$VENV_DIR"
    ok "Virtual environment created"
else
    ok "Virtual environment already exists, skipping creation"
fi

info "Installing Python dependencies"
"$VENV_DIR/bin/pip" install --quiet --upgrade pip
"$VENV_DIR/bin/pip" install --quiet bleak aiobmsble influxdb-client
ok "Dependencies installed"

# ── write config ──────────────────────────────────────────────────────────────

mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/daly.conf"

if [[ -f "$CONFIG_FILE" ]]; then
    warn "Config already exists at $CONFIG_FILE – backing up to ${CONFIG_FILE}.bak"
    cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
fi

cat > "$CONFIG_FILE" <<TOML
# Daly BMS Monitor configuration
# Generated by install.sh on $(date -Iseconds)

[logging]
level = "INFO"
interval = 60  # seconds between polls

[jsonl]
enabled = true
file_path = "$INSTALL_DIR/battery_data.jsonl"

[influxdb]
enabled = true
url = "$INFLUX_URL"
token = "$INFLUX_TOKEN"
org = "$INFLUX_ORG"
bucket = "$INFLUX_BUCKET"

[[batteries]]
name = "$BATTERY_NAME"
address = "$BATTERY_ADDR"

# Add more batteries by repeating the [[batteries]] block:
# [[batteries]]
# name = "Starterbatterie"
# address = "11:22:33:44:55:66"
TOML

chmod 600 "$CONFIG_FILE"   # token is sensitive
ok "Config written to $CONFIG_FILE (mode 600)"

# ── systemd user service ──────────────────────────────────────────────────────

mkdir -p "$HOME/.config/systemd/user"

cat > "$SERVICE_FILE" <<UNIT
[Unit]
Description=Daly BMS BLE monitoring daemon
After=network.target
Wants=network.target

[Service]
Type=simple
WorkingDirectory=$CONFIG_DIR
ExecStart=$VENV_DIR/bin/python $INSTALL_DIR/dalymon.py
Restart=on-failure
RestartSec=30
# Keep the config readable
UMask=0077

[Install]
WantedBy=default.target
UNIT

ok "Systemd service installed at $SERVICE_FILE"

# ── symlink config into install dir so dalymon.py finds it ───────────────────
# dalymon.py opens "daly.conf" relative to cwd; the service sets WorkingDirectory
# to $CONFIG_DIR, so no symlink is needed.  But mention the cwd clearly.

# ── enable & start ────────────────────────────────────────────────────────────

echo ""
systemctl --user daemon-reload
echo ""
read -rp "  Enable and start the dalymon service now? [Y/n] " yn_start
case "${yn_start:-Y}" in
    [Yy]*)
        systemctl --user enable --now dalymon
        echo ""
        ok "Service enabled and started"
        echo ""
        echo "  Check status : systemctl --user status dalymon"
        echo "  Follow logs  : journalctl --user-unit dalymon -f"
        ;;
    *)
        echo ""
        info "To start the service manually:"
        echo "    systemctl --user enable --now dalymon"
        ;;
esac

echo ""
echo "$(bold '✓ Installation complete')"
echo ""
echo "  Config file  : $CONFIG_FILE"
echo "  Install dir  : $INSTALL_DIR"
echo "  Service      : systemctl --user status dalymon"
echo ""
